import QtQuick 1.1
// Generated by meego/tests/make-stubs.sh from the real component;
// only the API surface, so that the checker sees what the device has.
Item {
    property url icon
    property int maxHeight
    property variant oldParent
    property url platformIcon
    property variant platformStyle
    property variant platformTitle
    property string platformTitleText
    property int status
    property variant style
    property variant title
    property string titleText
    property variant visualParent
    signal clicked()
    signal privateClicked()
    function close() {}
    function closeMenu() {}
    function logDeprecatedMsg(name) {}
    function open() {}
}
